# .streamlit/secrets.toml

# Key of API used (set model in config.py accordingly; only one key necessary)
API_KEY_OPENAI = "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"
API_KEY_ANTHROPIC = "addkeyhere"

# Section for account names and passwords
[passwords]

# Test account (can attempt interview multiple times)
testaccount = "testpw"

# Accounts in study (can attempt interview once)
# add further accounts in the format 'accountname = "password"' here
95u9kr3rm3 = "mr4cl168dq"

cc  = "passwhat"
nim_testing     = "testingpw"
jakob_testing   = "testingpw"